[package]
name = "log-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
env_logger = "0.11.3"
eyre = "0.6.12"
log = "0.4.21"
regex = "1.10.4"

[dev-dependencies]
tempfile = "3.10.1"
